-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS agenda.contacto
(
    id serial NOT NULL,
    nombre character varying(50) NOT NULL,
    numero_documento character varying(20) NOT NULL,
    direccion character varying(50) NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_modificacion timestamp with time zone NOT NULL,
    activo boolean NOT NULL DEFAULT true,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS agenda.telefono
(
    id serial NOT NULL,
    contacto_id integer,
    telefono character varying(20) NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_modificacion timestamp with time zone NOT NULL,
    activo boolean NOT NULL DEFAULT true,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS agenda.correo
(
    id serial NOT NULL,
    contacto_id integer,
    email character varying(30) NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_modificacion timestamp with time zone NOT NULL,
    activo boolean NOT NULL DEFAULT true,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS agenda.telefono
    ADD CONSTRAINT pk_telefono_contacto FOREIGN KEY (contacto_id)
    REFERENCES agenda.contacto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS agenda.correo
    ADD CONSTRAINT pk_correo_contacto FOREIGN KEY (contacto_id)
    REFERENCES agenda.contacto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;