swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /contacto_parametro/:
    get:
      tags:
      - contacto_parametro
      description: get Personas_parametros
      operationId: Personas_parametrosController.GetAll
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Personas_parametros'
        "403":
          description: ""
    post:
      tags:
      - contacto_parametro
      description: create Personas_parametros
      operationId: Personas_parametrosController.Create
      parameters:
      - in: body
        name: body
        description: body for Personas_parametros content
        required: true
        schema:
          $ref: '#/definitions/models.Personas_parametros'
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/models.Personas_parametros'
        "403":
          description: body is empty
  /contacto_parametro/{id}:
    get:
      tags:
      - contacto_parametro
      description: get Personas_parametros by id
      operationId: Personas_parametrosController.GetOne
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Personas_parametros'
        "403":
          description: :id is empty
    put:
      tags:
      - contacto_parametro
      description: update the Personas_parametros
      operationId: Personas_parametrosController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Personas_parametros content
        required: true
        schema:
          $ref: '#/definitions/models.Personas_parametros'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Personas_parametros'
        "403":
          description: :id is not int
    delete:
      tags:
      - contacto_parametro
      description: delete the Personas_parametros
      operationId: Personas_parametrosController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
definitions:
  models.Personas_parametros:
    title: Personas_parametros
    type: object
tags:
- name: contacto_parametro
  description: |
    Personas_parametrosController operations for Personas_parametros
